name: Build with PyInstaller

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.12]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build with PyInstaller
        run: pyinstaller --onefile --hidden-import=requests src/bnetza-parser.py

      - name: Archive production artifacts (Linux/macOS)
        if: runner.os != 'Windows'
        run: zip -r Executable-${{ runner.os }}.zip ./dist/*
      
      - name: Archive production artifacts (Windows)
        if: runner.os == 'Windows'
        run: Compress-Archive -Path dist\* -DestinationPath Executable-Windows.zip
        shell: pwsh

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Executable-${{ runner.os }}
          path: Executable-${{ runner.os }}.zip

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: build-${{ github.run_number }}
          name: Release ${{ github.run_number }}
          files: ./artifacts/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
