name: Build with PyInstaller

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.12.6]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build with PyInstaller
        run: |
          pyinstaller --onefile src/bnetza-parser.py 

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Executable-${{ runner.os }}
          path: ./dist/


      - name: Archive production artifacts
        run: |
          zip -r Executable-${{ runner.os }}.zip ./dist/*

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: build-${{ github.sha }}
          name: Release ${{ github.sha }}
          files: Executable-${{ runner.os }}.zip
          draft: false
          prerelease: false

      - name: Upload binaries
        uses: softprops/action-gh-release@v1
        with:
          files: |
            Executable-${{ runner.os }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
